from enum import Enum


class CommandType(Enum):
    SCREENSHOT = "screenshot"
    SYSTEM_STATUS = "system_status"
    LIST_FILES = "list_files"
    LIST_PROCESSES = "list_processes"
    RUN_COMMAND = "run_cmd"
    OPEN_APP = "open_app"
    CLOSE_APP = "close_app"
    DELETE_FILE = "delete_file"
    COPY_FILE = "copy_file"
    MOVE_FILE = "move_file"
    SHUTDOWN = "shutdown"
    RESTART = "restart"
    ANYDESK = "anydesk_start"
    DAILY_REPORT = "daily_report"
    CHAT = "chat"
    SECURITY_REPORT = "security_report"
    LOCK = "lock"
    VOLUME = "volume"
    OPEN_FILE = "open_file"
    SEARCH_FILES = "search_files"
    CANCEL_SHUTDOWN = "cancel_shutdown"
    ANYDESK_STOP = "anydesk_stop"
    ANYDESK_ID = "anydesk_id"
    WOL_START = "wol_start"
    WOL_NOTIFY = "wol_notify"
    WOL_STATUS = "wol_status"
    STREAM_START = "stream_start"
    STREAM_STOP = "stream_stop"
    STREAM_STATUS = "stream_status"
    SECURITY_BLOCK = "security_block"
    SECURITY_UNBLOCK = "security_unblock"
    WATCHDOG_STATUS = "watchdog_status"
    LOGOUT = "logout"
    SSH_EXEC = "ssh_exec"
    SSH_STATUS = "ssh_status"
    SSH_LIST = "ssh_list"
    SFTP_GET = "sftp_get"
    SFTP_PUT = "sftp_put"
    SSH_BORE_PORT = "ssh_bore_port"
